name: SuperManager
version: ${project.version}
main: xyz.theprogramsrc.supermanager.SuperManager
api-version: "1.13"
author: TheProgramSrc
description: ${project.description}
softdepend: ["PlaceholderAPI"]

permissions:
  supermanager.admin:
    description: Access to the SuperManager Admin GUI
    default: op

